version: '3.8'

services:
  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URI=neo4j://192.168.50.97:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=obinutriproject
      # - NEO4J_URI=neo4j+s://af4bec42.databases.neo4j.io
      # - NEO4J_USER=neo4j
      # - NEO4J_PASSWORD=vFz0dJgS3Lv-NQjK82zIuSiQGWWzsUS_ek-Xm32CZ0k
    # depends_on:
    #   - neo4j
    networks:
      - app-network

  # neo4j:
  #   image: neo4j:4.4
  #   ports:
  #     - "7474:7474"  # HTTP
  #     - "7688:7688"  # Bolt
  #   environment:
  #     - NEO4J_AUTH=neo4j/obinutriproject
  #     - NEO4J_dbms_memory_pagecache_size=1G
  #     - NEO4J_dbms_memory_heap_initial__size=1G
  #     - NEO4J_dbms_memory_heap_max__size=1G
  #   volumes:
  #     - neo4j_data:/data
  #     - neo4j_logs:/logs
  #   networks:
  #     - app-network

# volumes:
#   neo4j_data:
#   neo4j_logs:

networks:
  app-network:
    driver: bridge